// Generated by npm run versions:update from PaperMC Fill v3.
export const MINECRAFT_VERSIONS = [
    "26.2",
    "26.1",
    "1.21",
    "1.20",
    "1.19",
    "1.18",
    "1.17",
    "1.16",
    "1.15",
    "1.14",
    "1.13",
    "1.12",
    "1.11",
    "1.10",
    "1.9",
    "1.8",
    "1.7",
] as const;

export const MINECRAFT_VERSION_ENUM = [...MINECRAFT_VERSIONS, "null"]
    .map((version) => `"${version}"`)
    .join(",");
